### ISSUE TITLE
CombinedBinHClucAndMADV9 Custom Stoploss Error

### ISSUE THREAD

**Issue by MrHumanRebel** [i1ya/freqtrade-strategies#1]
2021-06-17 11:50:05,167 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error single positional indexer is out-of-bounds calling <bound method CombinedBinHClucAndMADV9.custom_stoploss of <CombinedBinHClucAndMADV9.CombinedBinHClucAndMADV9 object at 0x7fb99d607d90>>
Traceback (most recent call last):
  File "/home/develop/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/develop/freqtrade/user_data/strategies/CombinedBinHClucAndMADV9.py", line 172, in custom_stoploss
    candle = dataframe.iloc[-number_of_candle_shift].squeeze()
  File "/home/develop/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/develop/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/develop/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2021-06-17 11:50:05,167 - freqtrade - ERROR - single positional indexer is out-of-bounds

Latest c4bc47e FreqTrade
Bare Linux Mint Latest

**Comment by i1ya** [comment]
Hi!
Thanks for bug reporting.
Yeah, looks like some it happen with some pairs. Will fix it as soon as possible.
