### ISSUE TITLE
problem ask 

### ISSUE THREAD

**Issue by agustin9014** [i1ya/freqtrade-strategies#5]
Hi, I want to congratulate you on your excellent work. From already thank you very much
freqtrade22    | Traceback (most recent call last):
freqtrade22    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade22    |     worker = Worker(args)
freqtrade22    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade22    |     self._init(False)
freqtrade22    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade22    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade22    |   File "/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
freqtrade22    |     validate_config_consistency(config)
freqtrade22    |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 77, in validate_config_consistency
freqtrade22    |     _validate_price_config(conf)
freqtrade22    |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 106, in _validate_price_config
freqtrade22    |     raise OperationalException('Market buy orders require bid_strategy.price_side = "ask".')
freqtrade22    | freqtrade.exceptions.OperationalException: Market buy orders require bid_strategy.price_side = "ask".

**Comment by i1ya** [comment]
Hello!
Thank you man.
Last line clearly say what you have to do: Market buy orders require bid_strategy.price_side = "ask".

**Comment by agustin9014** [comment]
Thank you very much for your time, could you share an example of how bid_strategy.price_side goes in config.json

bid_strategy.price_side = "ask"

**Comment by i1ya** [comment]
This is my config.json:

    "bid_strategy": {
        "price_side": "ask",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "bid",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1
    },

But you better read about it in docs - https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders

**Comment by agustin9014** [comment]
thanks brother! I am happy with this project I want to donate

**Comment by agustin9014** [comment]
I don't want to abuse your kindness. Last query is normar in dashboard graph:
Buysignals: 0SellSignals: 0

**Comment by i1ya** [comment]
Try to check in backtest mode.
